---


fabric_name: PF_NETWORK

# This is needed for virtual/containerized EOS
bgp_update_wait_install: false

# Can also be just autovpn
wan_mode: cv-pathfinder

bgp_as: 65000


cv_pathfinder_regions:
  - name: REGION1
    id: 1
    sites:
      - name: SITE11
        id: 101
        location: Perris, CA
      - name: SITE12
        id: 102
        location: Lake Elsinore, CA
      - name: SITE13
        id: 103
        location: Byron, CA
      - name: SITE14
        id: 104
        location: San Jose, CA
      - name: SITE1_R1_PF
        id: 198
        location: San Francisco, CA


# You really want to use passwords here, as lots of critical info is reflected/served from these BGP servers

bgp_peer_groups:
  wan_overlay_peers:
    # password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 10.99.101.0/24
      - 10.99.102.0/24



# Wan_route_server is Pathfinder
wan_route_servers:
  - hostname: RR1
  - hostname: RR2


wan_ipsec_profiles:
  control_plane:
    shared_key: 0110100A480E0A0E231D1E
  data_plane:
    shared_key: 0110100A480E0A0E231D1E


wan_path_groups:
  - name: mpls_path
    id: 1001
  - name: internet_path
    id: 1002

wan_carriers:
  - name: mpls
    path_group: mpls_path
    trusted: true
  - name: internet
    path_group: internet_path
    trusted: true

wan_virtual_topologies:
  vrfs:
    - name: default
      policy: DEFAULT-AVT-POLICY
      wan_vni: 101
    - name: VRF_A
      policy: PROD-AVT-POLICY
      wan_vni: 102
  policies:
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [internet_path, mpls_path]
            preference: preferred
    - name: PROD-AVT-POLICY
      application_virtual_topologies:
        - application_profile: APP_1_PROFILE
          id: 6
          traffic_class: 3
          dscp: 26
          path_groups:
            - names: [internet_path]
              preference: alternate
            - names: [mpls_path]
              preference: preferred
        - application_profile: APP_2_PROFILE
          id: 5
          traffic_class: 2
          dscp: 18
          path_groups:
            - names: [internet_path]
              preference: alternate
            - names: [mpls_path]
              preference: preferred
      default_virtual_topology:
        traffic_class: 0
        dscp: 24
        constraints:
          latency: 15
          jitter: 3000
        path_groups:
          - names: [internet_path, mpls_path]
            preference: preferred
application_classification:
  field_sets:
    l4_ports:
      - name: APP_1_PORTS
        port_values:
          -  '80'
          -  '443'
      - name: APP_2_PORTS
        port_values:
          -  '5000'
  applications:
    ipv4_applications:
      - name: APP_1
        protocols:
          - 'tcp'
        tcp_dest_port_set_name: APP_1_PORTS
      - name: APP_2
        protocols:
          - 'tcp'
        tcp_dest_port_set_name: APP_2_PORTS
  application_profiles:
    - name: APP_1_PROFILE
      applications:
        - name: APP_1
    - name: APP_2_PROFILE
      applications:
        - name: APP_2


overlay_rt_type:
  admin_subfield: bgp_as
tenants:
  - name: TENANT_A
    vrfs:
      - name: default
        vrf_vni: 101
      - name: VRF_A
        vrf_vni: 102



