- name: Configuration deployment to CVaaS
  hosts: PF_NETWORK # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: www.arista.io
        cv_token: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjcwODkzNDMxODEzNjM3MTM3NTksImRzbiI6InRuZy0wNiIsImRzdCI6ImFjY291bnQiLCJleHAiOjE4MTkyOTkxMjAsImlhdCI6MTcyNDUxODMyMywib2dpIjo3MDg5MzQzMTgxMzYzNzAyMjQyLCJvZ24iOiJhcmlzdGEtdG5nLTA2Iiwic2lkIjoiMGY3NmI3NWNjYTUyMmZkZDcwMjk5ZWJjM2YzMzRjMWUwNDkzMTI4MGFkNmJmOWY3Y2VlYzhiMDdmODNmZDFkYi1HRmVyYUs5eTRrV1Z6SVlSbjlxcU1jVHpidVRnem5XUjloZ3EyYzlBIn0.mIrTrZ32RJp0wktw0IfC6GHdrq6KIBiE-GJ1bsHe6HoTXnuWIFTGM96D2dLlyxiQltydzdpTRuKY_T0JtzeRMQ"
        cv_run_change_control: true
# - name: Deploy config
#   hosts: PF_NETWORK
#   tasks:
#     - name: Deploy to CVaaS
#       run_once: true
#       delegate_to: localhost
#       arista.avd.cv_workflow:
#         cv_servers: ["www.arista.io"]
#         configuration_dir: "{{ inventory_dir }}/intended/configs"
#         structured_config_dir: "{{ inventory_dir }}/intended/structured_configs"
#         device_list: "{{ ansible_play_hosts }}"
#         workspace:
#           requested_state: submitted
#         change_control:
#           requested_state: pending approval
#         return_details: false


# ---
# - name: Apply configlets
#   hosts: cvaas

#   vars_files:
#     - ../vars/PF_Model.yml
#   tasks:
#     - name: Upload configlets
#       arista.cvp.cv_configlet_v3:
#         configlets: "{{ pf_configlets }}"
#     - name: Apply configlets
#       arista.cvp.cv_device_v3:
#         devices: "{{ pf_devices }}"
