---
all:
  hosts: 
    cvaas: 
      ansible_host: www.arista.io
      ansible_user: cvaas
      ansible_password: 
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False
      ansible_network_os: eos
      ansible_httpapi_port: 443
    # cvaas: 
    #   ansible_host: 192.168.0.5
    #   ansible_user: arista
    #   ansible_password: aristajqzo
    #   ansible_connection: httpapi
    #   ansible_httpapi_use_ssl: True
    #   ansible_httpapi_validate_certs: False
    #   ansible_network_os: eos
    #   ansible_httpapi_port: 443
  children:
    PF_NETWORK:
      children:
        pathfinder:
          hosts:
            RR1:
            RR2:
        REGIONS:
          children:
            REGION1:
              children:
                REGION1-EDGE:
                  children:
                    SITE11:
                      hosts:
                        Edge10:
                    SITE12:
                      hosts: 
                        Edge12:
                    SITE13:
                      hosts:
                        Edge13:
                    SITE14:
                      hosts:
                        Edge14:
                REGION1-TRANSIT:
                  hosts:
                    P10:
                    P11: